// 自动生成：人教版PEP 小学英语 3-6 年级 8 册 补充词汇岛（勿手改，见 tools/gen-extra.mjs）
// 覆盖：376 个课本单词 + 79 条课本短语
export const EXTRA_ISLANDS = [
  { key: "x3aw1", name: "三上拓展岛", emoji: "📗", color: "#FBE4D8", cx: -141, cz: 51.3, r: 18.58, style: "mixed",
    rows: [
      ["can", "可以", "三上课本词汇", "icon:🙆"],
      ["share", "分享", "三上课本词汇", "icon:🤲"],
      ["smile", "微笑", "三上课本词汇", "icon:😊"],
      ["listen", "听", "三上课本词汇", "icon:👂"],
      ["help", "帮助", "三上课本词汇", "icon:🆘"],
      ["say", "说", "三上课本词汇", "icon:💬"],
      ["and", "和", "三上课本词汇", "icon:➕"],
      ["good", "好的", "三上课本词汇", "icon:👍"],
      ["mum", "妈妈", "三上课本词汇", "icon:👩"],
      ["dad", "爸爸", "三上课本词汇", "icon:👨"],
      ["grandma", "奶奶", "三上课本词汇", "icon:👵"],
      ["grandpa", "爷爷", "三上课本词汇", "icon:👴"],
      ["me", "我", "三上课本词汇", "icon:🙋"],
      ["have", "有", "三上课本词汇", "icon:🤲"],
      ["cousin", "堂表兄妹", "三上课本词汇", "icon:🧒"],
      ["baby", "婴儿", "三上课本词汇", "icon:👶"],
      ["some", "一些", "三上课本词汇", "icon:🔸"],
      ["like", "喜欢", "三上课本词汇", "icon:❤️"],
      ["pet", "宠物", "三上课本词汇", "icon:🐾"],
      ["go", "去", "三上课本词汇", "icon:🚶"],
      ["Miss", "女士", "三上课本词汇", "icon:👩‍🏫"],
      ["cute", "可爱的", "三上课本词汇", "icon:🥰"],
      ["lion", "狮子", "三上课本词汇", "icon:🦁"],
      ["fast", "快的", "三上课本词汇", "icon:⚡"],
    ] },
  { key: "x3aw2", name: "三上拓展岛2", emoji: "📗", color: "#FBE4D8", cx: -108.9, cz: -108.9, r: 15.64, style: "mixed",
    rows: [
      ["air", "空气", "三上课本词汇", "icon:🌬️"],
      ["school", "学校", "三上课本词汇", "icon:🏫"],
      ["need", "需要", "三上课本词汇", "icon:🙏"],
      ["new", "新的", "三上课本词汇", "icon:✨"],
      ["give", "给", "三上课本词汇", "icon:🎁"],
      ["us", "我们", "三上课本词汇", "icon:👥"],
      ["them", "他们", "三上课本词汇", "icon:👉"],
      ["colour", "颜色", "三上课本词汇", "icon:🎨"],
      ["make", "制作", "三上课本词汇", "icon:🔨"],
      ["purple", "紫色", "三上课本词汇", "icon:🟣"],
      ["pink", "粉色", "三上课本词汇", "icon:🩷"],
      ["draw", "画", "三上课本词汇", "icon:✏️"],
      ["year", "年", "三上课本词汇", "icon:📅"],
      ["o'clock", "点钟", "三上课本词汇", "icon:🕐"],
      ["cut", "切", "三上课本词汇", "icon:✂️"],
      ["piece", "块", "三上课本词汇", "icon:🍰"],
      ["eat", "吃", "三上课本词汇", "icon:🍽️"],
    ] },
  { key: "x3ap1", name: "三上口语岛", emoji: "📗", color: "#FBE4D8", cx: 134.8, cz: 113.1, r: 11.02, style: "mixed",
    rows: [
      ["red panda", "小熊猫", "三上课本词汇", "phrase:🐼:red panda"],
      ["point to your ear", "指你的耳朵", "三上课本词汇", "phrase:👂:point to your ear"],
      ["wave your hand", "挥挥手", "三上课本词汇", "phrase:👋:wave your hand"],
      ["what's your name", "你叫什么名字", "三上课本词汇", "phrase:🪪:what's your name"],
      ["my name's", "我叫……", "三上课本词汇", "phrase:🪪:my name's"],
      ["show me your pencil", "给我看看你的铅笔", "三上课本词汇", "phrase:✏️:show me your pencil"],
    ] },
  { key: "x3bw1", name: "三下拓展岛", emoji: "📘", color: "#DCEAF5", cx: -61, cz: 137, r: 18.58, style: "pine",
    rows: [
      ["she", "她", "三下课本词汇", "icon:👧"],
      ["he", "他", "三下课本词汇", "icon:👦"],
      ["welcome", "欢迎", "三下课本词汇", "icon:🙌"],
      ["today", "今天", "三下课本词汇", "icon:📆"],
      ["from", "来自", "三下课本词汇", "icon:🌍"],
      ["pupil", "小学生", "三下课本词汇", "icon:🧑‍🎓"],
      ["tired", "累的", "三下课本词汇", "icon:😪"],
      ["feel", "感觉", "三下课本词汇", "icon:🤔"],
      ["love", "爱", "三下课本词汇", "icon:💖"],
      ["want", "要", "三下课本词汇", "icon:🙋"],
      ["drink", "喝", "三下课本词汇", "icon:🥤"],
      ["sleep", "睡觉", "三下课本词汇", "icon:😴"],
      ["play", "玩", "三下课本词汇", "icon:🎮"],
      ["bag", "书包", "三下课本词汇", "icon:👜"],
      ["read", "读", "三下课本词汇", "icon:📖"],
      ["write", "写", "三下课本词汇", "icon:✍️"],
      ["storybook", "故事书", "三下课本词汇", "icon:📕"],
      ["speak", "说", "三下课本词汇", "icon:🗣️"],
      ["hungry", "饿的", "三下课本词汇", "icon:🍽️"],
      ["doll", "洋娃娃", "三下课本词汇", "icon:🪆"],
      ["box", "盒子", "三下课本词汇", "icon:📦"],
      ["plane", "飞机", "三下课本词汇", "icon:✈️"],
      ["train", "火车", "三下课本词汇", "icon:🚆"],
      ["time", "时间", "三下课本词汇", "icon:⏰"],
    ] },
  { key: "x3bw2", name: "三下拓展岛2", emoji: "📘", color: "#DCEAF5", cx: 165.4, cz: -60.2, r: 10.5, style: "pine",
    rows: [
      ["yuan", "元", "三下课本词汇", "icon:💴"],
      ["many", "许多", "三下课本词汇", "icon:🔢"],
      ["people", "人", "三下课本词汇", "icon:👥"],
    ] },
  { key: "x3bp1", name: "三下口语岛", emoji: "📘", color: "#DCEAF5", cx: -149.4, cz: 13.1, r: 12.28, style: "pine",
    rows: [
      ["be from", "来自", "三下课本词汇", "phrase:🌍:be from"],
      ["a new student", "一名新学生", "三下课本词汇", "phrase:🧑‍🎓:a new student"],
      ["feel happy", "感到开心", "三下课本词汇", "phrase:😊:feel happy"],
      ["like dogs", "喜欢狗", "三下课本词汇", "phrase:🐕:like dogs"],
      ["write a word", "写字", "三下课本词汇", "phrase:✍️:write a word"],
      ["healthy food", "健康食物", "三下课本词汇", "phrase:🥗:healthy food"],
      ["toy box", "玩具盒", "三下课本词汇", "phrase:🧸:toy box"],
      ["on the desk", "在书桌上", "三下课本词汇", "phrase:🪑:on the desk"],
      ["what time", "几点", "三下课本词汇", "phrase:🕐:what time"],
    ] },
  { key: "x4aw1", name: "四上拓展岛", emoji: "📙", color: "#F5EEDC", cx: -18.3, cz: 148.9, r: 16.06, style: "house",
    rows: [
      ["fan", "风扇", "四上课本词汇", "icon:🌀"],
      ["really", "真的", "四上课本词汇", "icon:❗"],
      ["clean", "打扫", "四上课本词汇", "icon:🧹"],
      ["TV", "电视", "四上课本词汇", "icon:📺"],
      ["key", "钥匙", "四上课本词汇", "icon:🔑"],
      ["wow", "哇", "四上课本词汇", "icon:😮"],
      ["lost", "丢失", "四上课本词汇", "icon:🔍"],
      ["friendly", "友好的", "四上课本词汇", "icon:🤗"],
      ["or", "或者", "四上课本词汇", "icon:🔀"],
      ["right", "右边", "四上课本词汇", "icon:➡️"],
      ["find", "找到", "四上课本词汇", "icon:🔎"],
      ["ready", "准备好", "四上课本词汇", "icon:✅"],
      ["pass", "递", "四上课本词汇", "icon:🤝"],
      ["try", "尝试", "四上课本词汇", "icon:💪"],
      ["but", "但是", "四上课本词汇", "icon:↔️"],
      ["little", "小的", "四上课本词汇", "icon:🐭"],
      ["puppy", "小狗", "四上课本词汇", "icon:🐶"],
      ["basketball", "篮球", "四上课本词汇", "icon:🏀"],
    ] },
  { key: "x4ap1", name: "四上口语岛", emoji: "📙", color: "#F5EEDC", cx: 127.2, cz: 79.5, r: 16.06, style: "house",
    rows: [
      ["teacher's desk", "讲台", "四上课本词汇", "phrase:🧑‍🏫:teacher's desk"],
      ["maths book", "数学书", "四上课本词汇", "phrase:➗:maths book"],
      ["English book", "英语书", "四上课本词汇", "phrase:🔤:English book"],
      ["Chinese book", "语文书", "四上课本词汇", "phrase:📕:Chinese book"],
      ["so much", "非常", "四上课本词汇", "phrase:💯:so much"],
      ["help yourself", "请自便", "四上课本词汇", "phrase:🍽️:help yourself"],
      ["open the door", "开门", "四上课本词汇", "phrase:🚪:open the door"],
      ["sweep the floor", "扫地", "四上课本词汇", "phrase:🧹:sweep the floor"],
      ["turn on the light", "开灯", "四上课本词汇", "phrase:💡:turn on the light"],
      ["put up the picture", "张贴图画", "四上课本词汇", "phrase:🖼️:put up the picture"],
      ["clean the board", "擦黑板", "四上课本词汇", "phrase:🧽:clean the board"],
      ["close the window", "关窗户", "四上课本词汇", "phrase:🪟:close the window"],
      ["have a snack", "吃零食", "四上课本词汇", "phrase:🍪:have a snack"],
      ["have a nap", "打个盹", "四上课本词汇", "phrase:😴:have a nap"],
      ["make a salad", "做沙拉", "四上课本词汇", "phrase:🥗:make a salad"],
      ["pass me the bowl", "把碗递给我", "四上课本词汇", "phrase:🥣:pass me the bowl"],
      ["pass me the knife", "把刀递给我", "四上课本词汇", "phrase:🔪:pass me the knife"],
      ["cut the vegetables", "切蔬菜", "四上课本词汇", "phrase:🥕:cut the vegetables"],
    ] },
  { key: "x4ap2", name: "四上口语岛2", emoji: "📙", color: "#F5EEDC", cx: 57.3, cz: 166.4, r: 10.5, style: "house",
    rows: [
      ["use the spoon", "用勺子", "四上课本词汇", "phrase:🥄:use the spoon"],
      ["use the fork", "用叉子", "四上课本词汇", "phrase:🍴:use the fork"],
    ] },
  { key: "x4bw1", name: "四下拓展岛", emoji: "📕", color: "#E4F0E4", cx: 144.9, cz: 38.8, r: 18.58, style: "mixed",
    rows: [
      ["way", "方向", "四下课本词汇", "icon:🧭"],
      ["now", "现在", "四下课本词汇", "icon:⏱️"],
      ["kid", "小孩", "四下课本词汇", "icon:🧒"],
      ["thirty", "三十", "四下课本词汇", "icon:3️⃣0️⃣"],
      ["hurry", "快点", "四下课本词汇", "icon:🏃"],
      ["outside", "在户外", "四下课本词汇", "icon:🌤️"],
      ["degree", "度", "四下课本词汇", "icon:🌡️"],
      ["world", "世界", "四下课本词汇", "icon:🌏"],
      ["London", "伦敦", "四下课本词汇", "icon:🇬🇧"],
      ["Moscow", "莫斯科", "四下课本词汇", "icon:🇷🇺"],
      ["Singapore", "新加坡", "四下课本词汇", "icon:🇸🇬"],
      ["Sydney", "悉尼", "四下课本词汇", "icon:🇦🇺"],
      ["fly", "放风筝", "四下课本词汇", "icon:🪁"],
      ["yum", "味道好", "四下课本词汇", "icon:😋"],
      ["those", "那些", "四下课本词汇", "icon:👉"],
      ["clothes", "衣服", "四下课本词汇", "icon:👕"],
      ["pants", "裤子", "四下课本词汇", "icon:👖"],
      ["dress", "连衣裙", "四下课本词汇", "icon:👗"],
      ["skirt", "裙子", "四下课本词汇", "icon:🩱"],
      ["sock", "短袜", "四下课本词汇", "icon:🧦"],
      ["shorts", "短裤", "四下课本词汇", "icon:🩳"],
      ["yours", "你的", "四下课本词汇", "icon:👈"],
      ["mine", "我的", "四下课本词汇", "icon:🙋"],
      ["pack", "收拾行李", "四下课本词汇", "icon:🧳"],
    ] },
  { key: "x4bw2", name: "四下拓展岛2", emoji: "📕", color: "#E4F0E4", cx: -142.4, cz: -103.5, r: 10.5, style: "mixed",
    rows: [
      ["wait", "等待", "四下课本词汇", "icon:⏳"],
      ["glove", "手套", "四下课本词汇", "icon:🧤"],
      ["too", "太", "四下课本词汇", "icon:➕"],
    ] },
  { key: "x4bp1", name: "四下口语岛", emoji: "📕", color: "#E4F0E4", cx: 103.7, cz: 111.2, r: 12.28, style: "mixed",
    rows: [
      ["first floor", "一楼", "四下课本词汇", "phrase:1️⃣:first floor"],
      ["second floor", "二楼", "四下课本词汇", "phrase:2️⃣:second floor"],
      ["teacher's office", "教师办公室", "四下课本词汇", "phrase:🏢:teacher's office"],
      ["hurry up", "快点", "四下课本词汇", "phrase:🏃:hurry up"],
      ["come on", "加油", "四下课本词汇", "phrase:💪:come on"],
      ["be careful", "小心", "四下课本词汇", "phrase:⚠️:be careful"],
      ["how about", "怎么样", "四下课本词汇", "phrase:❔:how about"],
      ["New York", "纽约", "四下课本词汇", "phrase:🇺🇸:New York"],
      ["of course", "当然", "四下课本词汇", "phrase:👌:of course"],
    ] },
  { key: "x5aw1", name: "五上拓展岛", emoji: "📗", color: "#F0E4EC", cx: 65.8, cz: -134.8, r: 18.58, style: "house",
    rows: [
      ["know", "知道", "五上课本词汇", "icon:💡"],
      ["our", "我们的", "五上课本词汇", "icon:👨‍👩‍👧"],
      ["Ms", "女士", "五上课本词汇", "icon:👩"],
      ["will", "将要", "五上课本词汇", "icon:🔮"],
      ["sometime", "有时", "五上课本词汇", "icon:🕰️"],
      ["robot", "机器人", "五上课本词汇", "icon:🤖"],
      ["him", "他", "五上课本词汇", "icon:👦"],
      ["finish", "完成", "五上课本词汇", "icon:🏁"],
      ["wash", "洗", "五上课本词汇", "icon:🧼"],
      ["watch", "看", "五上课本词汇", "icon:👀"],
      ["often", "经常", "五上课本词汇", "icon:🔁"],
      ["park", "公园", "五上课本词汇", "icon:🌳"],
      ["sport", "运动", "五上课本词汇", "icon:⚽"],
      ["should", "应该", "五上课本词汇", "icon:☝️"],
      ["every", "每个", "五上课本词汇", "icon:🔂"],
      ["day", "天", "五上课本词汇", "icon:☀️"],
      ["schedule", "日程", "五上课本词汇", "icon:🗓️"],
      ["thirsty", "渴的", "五上课本词汇", "icon:🥵"],
      ["favourite", "最喜爱的", "五上课本词汇", "icon:⭐"],
      ["food", "食物", "五上课本词汇", "icon:🍲"],
      ["dear", "亲爱的", "五上课本词汇", "icon:💌"],
      ["onion", "洋葱", "五上课本词汇", "icon:🧅"],
      ["sing", "唱歌", "五上课本词汇", "icon:🎤"],
      ["song", "歌曲", "五上课本词汇", "icon:🎵"],
    ] },
  { key: "x5aw2", name: "五上拓展岛2", emoji: "📗", color: "#F0E4EC", cx: 20.9, cz: -148.5, r: 17.74, style: "house",
    rows: [
      ["cartoon", "漫画", "五上课本词汇", "icon:🖍️"],
      ["ping-pong", "乒乓球", "五上课本词汇", "icon:🏓"],
      ["party", "聚会", "五上课本词汇", "icon:🎉"],
      ["next", "下一个", "五上课本词汇", "icon:⏭️"],
      ["wonderful", "极好的", "五上课本词汇", "icon:🌟"],
      ["learn", "学习", "五上课本词汇", "icon:📚"],
      ["any", "任何", "五上课本词汇", "icon:❔"],
      ["problem", "问题", "五上课本词汇", "icon:❓"],
      ["send", "发送", "五上课本词汇", "icon:📤"],
      ["email", "电子邮件", "五上课本词汇", "icon:📧"],
      ["we'll", "将会", "五上课本词汇", "icon:🫱"],
      ["there", "那里", "五上课本词汇", "icon:📍"],
      ["grandparent", "祖父母", "五上课本词汇", "icon:👵"],
      ["their", "他们的", "五上课本词汇", "icon:👥"],
      ["lot", "大量", "五上课本词汇", "icon:📚"],
      ["move", "搬家", "五上课本词汇", "icon:🚚"],
      ["dirty", "脏的", "五上课本词汇", "icon:🧹"],
      ["everywhere", "到处", "五上课本词汇", "icon:🌐"],
      ["live", "居住", "五上课本词汇", "icon:🏠"],
      ["nature", "自然", "五上课本词汇", "icon:🏞️"],
      ["boating", "划船", "五上课本词汇", "icon:🛶"],
      ["high", "高的", "五上课本词汇", "icon:⬆️"],
    ] },
  { key: "x5ap1", name: "五上口语岛", emoji: "📗", color: "#F0E4EC", cx: -96.9, cz: 119.7, r: 11.86, style: "house",
    rows: [
      ["play football", "踢足球", "五上课本词汇", "phrase:⚽:play football"],
      ["play sport", "做运动", "五上课本词汇", "phrase:🏃:play sport"],
      ["kung fu", "功夫", "五上课本词汇", "phrase:🥋:kung fu"],
      ["no problem", "没问题", "五上课本词汇", "phrase:👌:no problem"],
      ["water bottle", "水瓶", "五上课本词汇", "phrase:🚰:water bottle"],
      ["in front of", "在……前面", "五上课本词汇", "phrase:⬆️:in front of"],
      ["lots of", "大量", "五上课本词汇", "phrase:🔢:lots of"],
      ["go boating", "去划船", "五上课本词汇", "phrase:🛶:go boating"],
    ] },
  { key: "x5bw1", name: "五下拓展岛", emoji: "📘", color: "#E8E8F5", cx: 129.9, cz: -75, r: 18.58, style: "pine",
    rows: [
      ["after", "在……之后", "五下课本词汇", "icon:⏭️"],
      ["start", "开始", "五下课本词汇", "icon:🚦"],
      ["usually", "通常", "五下课本词汇", "icon:🔁"],
      ["Spain", "西班牙", "五下课本词汇", "icon:🇪🇸"],
      ["late", "迟到", "五下课本词汇", "icon:⌛"],
      ["why", "为什么", "五下课本词汇", "icon:❔"],
      ["shop", "购物", "五下课本词汇", "icon:🛍️"],
      ["work", "工作", "五下课本词汇", "icon:💼"],
      ["last", "上一个", "五下课本词汇", "icon:⏮️"],
      ["sound", "听起来", "五下课本词汇", "icon:🔊"],
      ["also", "也", "五下课本词汇", "icon:➕"],
      ["busy", "忙的", "五下课本词汇", "icon:🐝"],
      ["letter", "信", "五下课本词汇", "icon:✉️"],
      ["for", "为了", "五下课本词汇", "icon:🎯"],
      ["island", "岛", "五下课本词汇", "icon:🏝️"],
      ["always", "总是", "五下课本词汇", "icon:♾️"],
      ["cave", "山洞", "五下课本词汇", "icon:🕳️"],
      ["win", "获胜", "五下课本词汇", "icon:🏆"],
      ["exercise", "运动", "五下课本词汇", "icon:🤸"],
      ["take", "上（课）", "五下课本词汇", "icon:🤲"],
      ["pick", "摘", "五下课本词汇", "icon:🧺"],
      ["snowman", "雪人", "五下课本词汇", "icon:⛄"],
      ["snow", "雪", "五下课本词汇", "icon:❄️"],
      ["because", "因为", "五下课本词汇", "icon:➡️"],
    ] },
  { key: "x5bw2", name: "五下拓展岛2", emoji: "📘", color: "#E8E8F5", cx: -133.7, cz: -68.1, r: 18.58, style: "pine",
    rows: [
      ["vacation", "假期", "五下课本词汇", "icon:🏖️"],
      ["all", "全部", "五下课本词汇", "icon:💯"],
      ["lovely", "可爱的", "五下课本词汇", "icon:🥰"],
      ["fall", "落下", "五下课本词汇", "icon:🍂"],
      ["paint", "绘画", "五下课本词汇", "icon:🎨"],
      ["contest", "比赛", "五下课本词汇", "icon:🏅"],
      ["few", "一些", "五下课本词汇", "icon:🔢"],
      ["thing", "事情", "五下课本词汇", "icon:📦"],
      ["meet", "集会", "五下课本词汇", "icon:🤝"],
      ["trip", "旅行", "五下课本词汇", "icon:🧳"],
      ["national", "国家的", "五下课本词汇", "icon:🚩"],
      ["American", "美国的", "五下课本词汇", "icon:🇺🇸"],
      ["Thanksgiving", "感恩节", "五下课本词汇", "icon:🦃"],
      ["fool", "傻瓜", "五下课本词汇", "icon:🤪"],
      ["kitten", "小猫", "五下课本词汇", "icon:🐱"],
      ["diary", "日记", "五下课本词汇", "icon:📔"],
      ["still", "仍然", "五下课本词汇", "icon:⏸️"],
      ["noise", "噪音", "五下课本词汇", "icon:📢"],
      ["fur", "软毛", "五下课本词汇", "icon:🧸"],
      ["open", "开着的", "五下课本词汇", "icon:📂"],
      ["walk", "行走", "五下课本词汇", "icon:🚶"],
      ["first", "第一", "五下课本词汇", "icon:🥇"],
      ["second", "第二", "五下课本词汇", "icon:🥈"],
      ["third", "第三", "五下课本词汇", "icon:🥉"],
    ] },
  { key: "x5bw3", name: "五下拓展岛3", emoji: "📘", color: "#E8E8F5", cx: -148.2, cz: -23.5, r: 18.16, style: "pine",
    rows: [
      ["fourth", "第四", "五下课本词汇", "icon:4️⃣"],
      ["fifth", "第五", "五下课本词汇", "icon:5️⃣"],
      ["twelfth", "第十二", "五下课本词汇", "icon:1️⃣2️⃣"],
      ["twentieth", "第二十", "五下课本词汇", "icon:2️⃣0️⃣"],
      ["twenty-first", "第二十一", "五下课本词汇", "icon:2️⃣1️⃣"],
      ["hers", "她的", "五下课本词汇", "icon:👩"],
      ["theirs", "他们的", "五下课本词汇", "icon:👥"],
      ["ours", "我们的", "五下课本词汇", "icon:🏠"],
      ["each", "每个", "五下课本词汇", "icon:🔂"],
      ["other", "其他的", "五下课本词汇", "icon:👥"],
      ["excited", "兴奋的", "五下课本词汇", "icon:🤩"],
      ["its", "它的", "五下课本词汇", "icon:🐾"],
      ["show", "指引", "五下课本词汇", "icon:👉"],
      ["anything", "任何事物", "五下课本词汇", "icon:❓"],
      ["else", "其他", "五下课本词汇", "icon:➕"],
      ["exhibition", "展览", "五下课本词汇", "icon:🖼️"],
      ["sushi", "寿司", "五下课本词汇", "icon:🍣"],
      ["teach", "教", "五下课本词汇", "icon:👩‍🏫"],
      ["Canadian", "加拿大的", "五下课本词汇", "icon:🇨🇦"],
      ["Spanish", "西班牙的", "五下课本词汇", "icon:🇪🇸"],
      ["keep", "保持", "五下课本词汇", "icon:🔒"],
      ["turn", "顺序", "五下课本词汇", "icon:🔄"],
      ["bamboo", "竹子", "五下课本词汇", "icon:🎋"],
    ] },
  { key: "x5bp1", name: "五下口语岛", emoji: "📘", color: "#E8E8F5", cx: 108.9, cz: -108.9, r: 13.54, style: "pine",
    rows: [
      ["go on a picnic", "去野餐", "五下课本词汇", "phrase:🧺:go on a picnic"],
      ["good job", "做得好", "五下课本词汇", "phrase:👍:good job"],
      ["a few", "一些", "五下课本词汇", "phrase:🔢:a few"],
      ["sports meet", "运动会", "五下课本词汇", "phrase:🏟️:sports meet"],
      ["Tree Planting Day", "植树节", "五下课本词汇", "phrase:🌳:Tree Planting Day"],
      ["the Great Wall", "长城", "五下课本词汇", "phrase:🧱:the Great Wall"],
      ["each other", "互相", "五下课本词汇", "phrase:🤝:each other"],
      ["have a look", "看一看", "五下课本词汇", "phrase:👀:have a look"],
      ["keep to the right", "靠右", "五下课本词汇", "phrase:➡️:keep to the right"],
      ["keep your desk clean", "保持课桌整洁", "五下课本词汇", "phrase:🧹:keep your desk clean"],
      ["talk quietly", "小声说话", "五下课本词汇", "phrase:🤫:talk quietly"],
      ["take turns", "按顺序来", "五下课本词汇", "phrase:🔄:take turns"],
    ] },
  { key: "x6aw1", name: "六上拓展岛", emoji: "📙", color: "#E4EEF5", cx: -72.7, cz: -131.2, r: 18.58, style: "mixed",
    rows: [
      ["science", "科学", "六上课本词汇", "icon:🔬"],
      ["museum", "博物馆", "六上课本词汇", "icon:🏛️"],
      ["left", "左边", "六上课本词汇", "icon:⬅️"],
      ["straight", "笔直地", "六上课本词汇", "icon:⬆️"],
      ["ask", "问", "六上课本词汇", "icon:🙋"],
      ["sir", "先生", "六上课本词汇", "icon:🎩"],
      ["interesting", "有趣的", "六上课本词汇", "icon:🤩"],
      ["italian", "意大利的", "六上课本词汇", "icon:🇮🇹"],
      ["restaurant", "餐馆", "六上课本词汇", "icon:🍽️"],
      ["pizza", "比萨", "六上课本词汇", "icon:🍕"],
      ["street", "街道", "六上课本词汇", "icon:🛣️"],
      ["get", "到达", "六上课本词汇", "icon:📍"],
      ["GPS", "定位系统", "六上课本词汇", "icon:🗺️"],
      ["gave", "给（过去式）", "六上课本词汇", "icon:🎁"],
      ["feature", "特点", "六上课本词汇", "icon:🔍"],
      ["follow", "跟随", "六上课本词汇", "icon:👣"],
      ["far", "远的", "六上课本词汇", "icon:🔭"],
      ["tell", "告诉", "六上课本词汇", "icon:🗣️"],
      ["by", "乘", "六上课本词汇", "icon:🚏"],
      ["bus", "公交车", "六上课本词汇", "icon:🚌"],
      ["taxi", "出租车", "六上课本词汇", "icon:🚕"],
      ["subway", "地铁", "六上课本词汇", "icon:🚇"],
      ["slow", "慢的", "六上课本词汇", "icon:🐢"],
      ["down", "向下", "六上课本词汇", "icon:⬇️"],
    ] },
  { key: "x6aw2", name: "六上拓展岛2", emoji: "📙", color: "#E4EEF5", cx: 72.7, cz: 131.2, r: 18.58, style: "mixed",
    rows: [
      ["Mrs", "夫人", "六上课本词汇", "icon:👩"],
      ["early", "早的", "六上课本词汇", "icon:🌅"],
      ["helmet", "头盔", "六上课本词汇", "icon:⛑️"],
      ["must", "必须", "六上课本词汇", "icon:❗"],
      ["wear", "穿戴", "六上课本词汇", "icon:👔"],
      ["attention", "注意", "六上课本词汇", "icon:⚠️"],
      ["traffic", "交通", "六上课本词汇", "icon:🚦"],
      ["Munich", "慕尼黑", "六上课本词汇", "icon:🇩🇪"],
      ["Germany", "德国", "六上课本词汇", "icon:🇩🇪"],
      ["Alaska", "阿拉斯加", "六上课本词汇", "icon:🇺🇸"],
      ["sled", "雪橇", "六上课本词汇", "icon:🛷"],
      ["ferry", "轮渡", "六上课本词汇", "icon:⛴️"],
      ["Scotland", "苏格兰", "六上课本词汇", "icon:🏴"],
      ["visit", "拜访", "六上课本词汇", "icon:🚪"],
      ["film", "电影", "六上课本词汇", "icon:🎬"],
      ["evening", "晚上", "六上课本词汇", "icon:🌆"],
      ["comic", "滑稽的", "六上课本词汇", "icon:💭"],
      ["word", "单词", "六上课本词汇", "icon:🔤"],
      ["postcard", "明信片", "六上课本词汇", "icon:📮"],
      ["lesson", "课", "六上课本词汇", "icon:📖"],
      ["space", "太空", "六上课本词汇", "icon:🚀"],
      ["travel", "旅行", "六上课本词汇", "icon:✈️"],
      ["half", "一半", "六上课本词汇", "icon:➗"],
      ["price", "价格", "六上课本词汇", "icon:💰"],
    ] },
  { key: "x6aw3", name: "六上拓展岛3", emoji: "📙", color: "#E4EEF5", cx: 147.2, cz: -28.6, r: 18.58, style: "mixed",
    rows: [
      ["together", "一起", "六上课本词汇", "icon:🤝"],
      ["mooncake", "月饼", "六上课本词汇", "icon:🥮"],
      ["poem", "诗", "六上课本词汇", "icon:📜"],
      ["studies", "学习", "六上课本词汇", "icon:📖"],
      ["puzzle", "谜", "六上课本词汇", "icon:🧩"],
      ["hiking", "远足", "六上课本词汇", "icon:🥾"],
      ["jasmine", "茉莉", "六上课本词汇", "icon:🌸"],
      ["idea", "主意", "六上课本词汇", "icon:💡"],
      ["Canberra", "堪培拉", "六上课本词汇", "icon:🇦🇺"],
      ["amazing", "惊奇的", "六上课本词汇", "icon:🤩"],
      ["shall", "将要", "六上课本词汇", "icon:🙋"],
      ["goal", "射门", "六上课本词汇", "icon:🥅"],
      ["join", "加入", "六上课本词汇", "icon:🤝"],
      ["club", "俱乐部", "六上课本词汇", "icon:🎪"],
      ["factory", "工厂", "六上课本词汇", "icon:🏭"],
      ["worker", "工人", "六上课本词汇", "icon:👷"],
      ["country", "国家", "六上课本词汇", "icon:🌍"],
      ["stay", "保持", "六上课本词汇", "icon:🏠"],
      ["university", "大学", "六上课本词汇", "icon:🎓"],
      ["if", "如果", "六上课本词汇", "icon:❓"],
      ["use", "使用", "六上课本词汇", "icon:🔧"],
      ["type", "打字", "六上课本词汇", "icon:⌨️"],
      ["quickly", "快速地", "六上课本词汇", "icon:💨"],
      ["secretary", "秘书", "六上课本词汇", "icon:💼"],
    ] },
  { key: "x6aw4", name: "六上拓展岛4", emoji: "📙", color: "#E4EEF5", cx: -123, cz: 89.3, r: 16.06, style: "mixed",
    rows: [
      ["more", "更多的", "六上课本词汇", "icon:➕"],
      ["deep", "深的", "六上课本词汇", "icon:🌊"],
      ["breath", "呼吸", "六上课本词汇", "icon:🫁"],
      ["count", "数数", "六上课本词汇", "icon:🔢"],
      ["chase", "追赶", "六上课本词汇", "icon:🏃"],
      ["mice", "老鼠（复数）", "六上课本词汇", "icon:🐭"],
      ["bad", "坏的", "六上课本词汇", "icon:👎"],
      ["hurt", "受伤", "六上课本词汇", "icon:🤕"],
      ["ill", "生病的", "六上课本词汇", "icon:🤒"],
      ["wrong", "有毛病", "六上课本词汇", "icon:❌"],
      ["well", "健康的", "六上课本词汇", "icon:💪"],
      ["sit", "坐", "六上课本词汇", "icon:🪑"],
      ["hear", "听见", "六上课本词汇", "icon:👂"],
      ["ant", "蚂蚁", "六上课本词汇", "icon:🐜"],
      ["worry", "担心", "六上课本词汇", "icon:😟"],
      ["stuck", "陷住", "六上课本词汇", "icon:🪤"],
      ["mud", "泥", "六上课本词汇", "icon:🟤"],
      ["pull", "拉", "六上课本词汇", "icon:🪢"],
    ] },
  { key: "x6ap1", name: "六上口语岛", emoji: "📙", color: "#E4EEF5", cx: 161.9, cz: 5.7, r: 11.86, style: "mixed",
    rows: [
      ["pay attention to", "注意", "六上课本词汇", "phrase:⚠️:pay attention to"],
      ["word book", "单词书", "六上课本词汇", "phrase:📖:word book"],
      ["Mid-autumn Festival", "中秋节", "六上课本词汇", "phrase:🥮:Mid-autumn Festival"],
      ["get together", "聚会", "六上课本词汇", "phrase:🎉:get together"],
      ["have an art lesson", "上美术课", "六上课本词汇", "phrase:🎨:have an art lesson"],
      ["go to the cinema", "去看电影", "六上课本词汇", "phrase:🎬:go to the cinema"],
      ["do more exercise", "多做运动", "六上课本词汇", "phrase:🏃:do more exercise"],
      ["Papa Westray", "帕帕韦斯特雷岛", "六上课本词汇", "phrase:🏝️:Papa Westray"],
    ] },
  { key: "x6bw1", name: "六下拓展岛", emoji: "📕", color: "#F0E8DC", cx: 26, cz: 147.7, r: 18.58, style: "house",
    rows: [
      ["dinosaur", "恐龙", "六下课本词汇", "icon:🦕"],
      ["hall", "大厅", "六下课本词汇", "icon:🏛️"],
      ["metre", "米", "六下课本词汇", "icon:📏"],
      ["than", "比", "六下课本词汇", "icon:⚖️"],
      ["both", "两个都", "六下课本词汇", "icon:✌️"],
      ["kilogram", "千克", "六下课本词汇", "icon:⚖️"],
      ["countryside", "乡村", "六下课本词汇", "icon:🌾"],
      ["lower", "更低的", "六下课本词汇", "icon:⬇️"],
      ["shadow", "影子", "六下课本词汇", "icon:🌑"],
      ["smarter", "更聪明的", "六下课本词汇", "icon:🧠"],
      ["become", "变成", "六下课本词汇", "icon:🔄"],
      ["cleaned", "打扫（过去式）", "六下课本词汇", "icon:🧹"],
      ["stayed", "停留（过去式）", "六下课本词汇", "icon:🏠"],
      ["washed", "洗（过去式）", "六下课本词汇", "icon:🧼"],
      ["watched", "看（过去式）", "六下课本词汇", "icon:📺"],
      ["had", "有（过去式）", "六下课本词汇", "icon:🎁"],
      ["saw", "看见（过去式）", "六下课本词汇", "icon:👀"],
      ["before", "在……之前", "六下课本词汇", "icon:⏪"],
      ["drank", "喝（过去式）", "六下课本词汇", "icon:🥤"],
      ["magazine", "杂志", "六下课本词汇", "icon:📰"],
      ["better", "更好的", "六下课本词汇", "icon:👍"],
      ["faster", "更快的", "六下课本词汇", "icon:🐇"],
      ["hotel", "旅馆", "六下课本词汇", "icon:🏨"],
      ["fixed", "修理（过去式）", "六下课本词汇", "icon:🔧"],
    ] },
  { key: "x6bw2", name: "六下拓展岛2", emoji: "📕", color: "#F0E8DC", cx: -28.6, cz: -147.2, r: 18.58, style: "house",
    rows: [
      ["broken", "破损的", "六下课本词汇", "icon:💔"],
      ["lamp", "台灯", "六下课本词汇", "icon:💡"],
      ["loud", "大声的", "六下课本词汇", "icon:📢"],
      ["enjoy", "享受", "六下课本词汇", "icon:😄"],
      ["went", "去（过去式）", "六下课本词汇", "icon:🚶"],
      ["camp", "野营", "六下课本词汇", "icon:🏕️"],
      ["fishing", "钓鱼", "六下课本词汇", "icon:🎣"],
      ["rode", "骑（过去式）", "六下课本词汇", "icon:🚲"],
      ["ate", "吃（过去式）", "六下课本词汇", "icon:🍽️"],
      ["took", "拍（过去式）", "六下课本词汇", "icon:📷"],
      ["bought", "买（过去式）", "六下课本词汇", "icon:🛒"],
      ["gift", "礼物", "六下课本词汇", "icon:🎁"],
      ["fell", "摔倒（过去式）", "六下课本词汇", "icon:🤕"],
      ["off", "落下", "六下课本词汇", "icon:⬇️"],
      ["Turpan", "吐鲁番", "六下课本词汇", "icon:🇨🇳"],
      ["could", "能（过去式）", "六下课本词汇", "icon:💪"],
      ["till", "直到", "六下课本词汇", "icon:⏳"],
      ["beach", "海滩", "六下课本词汇", "icon:🏖️"],
      ["basket", "篮子", "六下课本词汇", "icon:🧺"],
      ["part", "角色", "六下课本词汇", "icon:🎭"],
      ["licked", "舔（过去式）", "六下课本词汇", "icon:👅"],
      ["laughed", "笑（过去式）", "六下课本词汇", "icon:😂"],
      ["easy", "容易的", "六下课本词汇", "icon:👌"],
      ["different", "不同的", "六下课本词汇", "icon:🌈"],
    ] },
  { key: "x6bw3", name: "六下拓展岛3", emoji: "📕", color: "#F0E8DC", cx: 102.3, cz: -140.8, r: 11.86, style: "house",
    rows: [
      ["active", "积极的", "六下课本词汇", "icon:🏃"],
      ["race", "赛跑", "六下课本词汇", "icon:🏁"],
      ["nothing", "没有什么", "六下课本词汇", "icon:🚫"],
      ["thought", "想（过去式）", "六下课本词汇", "icon:💭"],
      ["felt", "感觉（过去式）", "六下课本词汇", "icon:🤗"],
      ["woke", "醒（过去式）", "六下课本词汇", "icon:⏰"],
      ["cheetah", "猎豹", "六下课本词汇", "icon:🐆"],
      ["dream", "梦", "六下课本词汇", "icon:💤"],
    ] },
  { key: "x6bp1", name: "六下口语岛", emoji: "📕", color: "#F0E8DC", cx: -3.1, cz: -176, r: 11.44, style: "house",
    rows: [
      ["fell off", "摔倒", "六下课本词汇", "phrase:🤕:fell off"],
      ["ate fresh food", "吃新鲜食物", "六下课本词汇", "phrase:🥗:ate fresh food"],
      ["Labour Day", "劳动节", "六下课本词汇", "phrase:🛠️:Labour Day"],
      ["go cycling", "去骑车", "六下课本词汇", "phrase:🚴:go cycling"],
      ["play badminton", "打羽毛球", "六下课本词汇", "phrase:🏸:play badminton"],
      ["last month", "上个月", "六下课本词汇", "phrase:📅:last month"],
      ["last year", "去年", "六下课本词汇", "phrase:📅:last year"],
    ] },
];
